spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: leedjik1531@gmail.com
    password: pqwddfbumhoihvsz
    properties:
      mail:
        smtp:
          starttls:
            enable: true



