spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: leedjik1531@gmail.com
    password: pqwddfbumhoihvsz
    properties:
      mail:
        smtp:
          starttls:
            enable: true

mybatis:
  mapper-locations: mybatis/**/*.xml  # XML 위치
  configuration:
    map-underscore-to-camel-case: true # underscore를 camel로 자동으로 바꿔주기
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 로그 찍기

